project_id = "jucngvlcnxjyvjxydmco"

[functions.check-flight-status]
verify_jwt = false

[functions.flight-status-cron]
verify_jwt = false

[functions.parse-travel-email]
verify_jwt = false

[functions.ai-receipt-scan]
verify_jwt = false

[functions.scan-gmail]
verify_jwt = false
